bref:
  team: jtech

service: laravel

# Set your team ID if you are using Bref Cloud
#bref:
#    team: my-team-id

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: ap-southeast-1
    # Environment variables
    environment:
        APP_ENV: production # Or use ${sls:stage} if you want the environment to match the stage
        APP_DEBUG: true # Set to true only for debugging
        APP_KEY: ${ssm:/laravel/prod/APP_KEY} # Set this to your Laravel app key
        DB_CONNECTION: mysql # Change to your database connection
        DB_URL: ${ssm:/laravel/prod/DB_URL}
        SESSION_DRIVER: database # Change to database if you have set up a database
        ASSET_URL: https://pub-ccfb6450958b4c0e9947a2f1f9c329c4.r2.dev/ # Change to your domain
        R2_ACCESS_KEY_ID: ${ssm:/laravel/prod/AWS_KEY}
        R2_SECRET_ACCESS_KEY: ${ssm:/laravel/prod/AWS_SECRET_LEY}
        R2_DEFAULT_REGION: ap-southeast-1 # Change to your region
        R2_BUCKET: jhayao # Change to your bucket name
        FILESYSTEM_DISK: r2
        R2_ENDPOINT: https://e20d459564b5296f048f8ac255bd5b81.r2.cloudflarestorage.com
        R2_URL: https://pub-e64b48d6794a40709a9461dc60f7f881.r2.dev # Change to your bucket URL



package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!resources/css/**'
        - '!resources/images/**'
        - '!resources/js/**'
        - '!storage/**'
        - '!tests/**'
        - '!database/*.sqlite'
        # Exclude assets except for the manifest file
        - '!public/build/**'
        - 'public/build/manifest.json'

functions:

    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        runtime: php-82-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-82-console
        timeout: 720 # in seconds
        # Uncomment to also run the scheduler every minute
        #events:
        #    - schedule:
        #          rate: rate(1 minute)
        #          input: '"schedule:run"'

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
